require 'rubygems'
require 'rake'
require 'rake/clean'
require 'pho'

BASE_DIR="/home/ldodds/data/space"

NSSDC_DIR="#{BASE_DIR}/nssdc"
NSSDC_CACHE_DIR="#{NSSDC_DIR}/cache"
NSSDC_DATA_DIR="#{NSSDC_DIR}/data"

APOLLO_DIR="#{BASE_DIR}/apollo"
APOLLO_CACHE_DIR="#{APOLLO_DIR}/cache"
APOLLO_DATA_DIR="#{APOLLO_DIR}/data"

STATIC_DATA_DIR="etc/static"

USER="ldodds"
PASS="XXXXXX"
STORENAME="http://api.talis.com/stores/space"

CLEAN.include ["#{NSSDC_DATA_DIR}/*.rdf", "#{NSSDC_DATA_DIR}/*.ok", "#{NSSDC_DATA_DIR}/*.fail", 
               "#{APOLLO_DATA_DIR}/*.rdf", "#{APOLLO_DATA_DIR}/*.ok", "#{APOLLO_DATA_DIR}/*.fail", 
               "#{STATIC_DATA_DIR}/*.ok", "#{STATIC_DATA_DIR}/*.fail"]

STORE = Pho::Store.new(STORENAME, USER, PASS)

task :cache_spacecraft do
  sh %{ruby bin/nssdc-cache.rb #{NSSDC_CACHE_DIR}}end

task :spacecraft => [:cache_spacecraft, :convert_spacecraft_batch]

#Creates one file per craft
task :convert_spacecraft do
  sh %{ruby bin/nssdc-spacecraft.rb #{NSSDC_CACHE_DIR} #{NSSDC_DATA_DIR} }  
end

#Batches for faster upload
task :convert_spacecraft_batch do
  sh %{ruby bin/nssdc-spacecraft-batch.rb #{NSSDC_CACHE_DIR} #{NSSDC_DATA_DIR} }  
end

task :upload_spacecraft do
  collection = Pho::RDFCollection.new(STORE, NSSDC_DATA_DIR)
  puts "Uploading spacecraft"
  collection.store()
  puts collection.summary()end

task :apollo do
  sh %{ruby bin/apollo-data.rb #{APOLLO_CACHE_DIR} #{APOLLO_DATA_DIR} }  
end

task :upload_apollo do
  collection = Pho::RDFCollection.new(STORE, APOLLO_DATA_DIR)
  puts "Uploading apollo data"
  collection.store()
  puts collection.summary()
end

task :upload_static do
  collection = Pho::RDFCollection.new(STORE, STATIC_DATA_DIR)
  puts "Uploading static data"
  collection.store()
  puts collection.summary()
end

#Run SPARQL construct queries from etc/sparql to add in extra data
task :infer do
  
  Dir.glob("etc/sparql/construct*.rq").each do |file|
    print "Executing #{file}..."
    query = File.new(file).read()
    resp = Pho::Enrichment::StoreEnricher.infer(STORE, query)
    puts resp.status
  end
    
end

task :convert => [:spacecraft, :apollo]

task :upload => [:upload_spacecraft, :upload_apollo, :upload_static]


#TODO tasks for:
# complete rebuild
# upload config
# upload content

